import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as http from 'http';
import { spawn } from 'child_process';

const BIN_PATH = path.resolve(__dirname, '..', '..', 'bin', 'ef.js');
import { renderClaudeSection, applyAgentGuidance, installBundledSkills, installSessionHook, stampedGuidanceVersion, guidanceVersion, GUIDANCE_FILES, CURSOR_FRONTMATTER } from '../src/commands/claude';

test('renderClaudeSection ports the .cursor template/backend-script/CRM docs', () => {
    const s = renderClaudeSection();
    for (const needle of ["asset('/main.css')", '@foreach(', '@component(', '@extends(', '<template-if', '[[ expression ]]', 'CRM functions', 'COLLECTION_CODE', 'saveMode', 'efmeta']) {
        assert.ok(s.includes(needle), `guidance should mention ${needle}`);
    }
});

/*
 * This locks in the fact that cost a live page. The CRM functions are
 * registered TWICE with different casing — PascalCase in the template engine
 * (CrmAdapter), camelCase in the backend-script runtime (BackendCodeService) —
 * and the sets are not identical. An agent called `CreateCrmEntry` (template
 * only) inside a backend script; the undefined function broke the render and
 * the domain served 404 until it was rolled back.
 */
test('guidance splits CRM functions by runtime instead of picking one casing', () => {
    const s = renderClaudeSection();

    // Both real sets must be present, with their own casing.
    for (const template of ['CreateCrmEntry', 'SetCrmRelation', 'EnsureCrmEntity']) {
        assert.ok(s.includes(template), `template-engine function ${template} must be listed`);
    }
    for (const script of ['setCrmFields', 'addCrmFieldValue', 'reassignCrmReference', 'ensureCrmEntity']) {
        assert.ok(s.includes(script), `backend-script function ${script} must be listed`);
    }

    // The trap itself, stated explicitly.
    assert.match(s, /not interchangeable/i, 'says the two sets cannot be swapped');
    assert.match(s, /only in templates/i, 'marks the template-only functions');
    assert.match(s, /only in backend scripts/i, 'marks the script-only functions');
    assert.ok(s.includes('there is no `createCrmEntry`'), 'states that the camelCase spelling does not exist');
    assert.match(s, /404/, 'says what actually happens when the name is wrong');
});

test('guidance links the authoritative docs and tells the agent to run --help', () => {
    const s = renderClaudeSection();
    assert.ok(s.includes('https://docs.elasticfunnels.io/backend-scripts/data-functions'), 'data-functions reference');
    assert.ok(s.includes('https://docs.elasticfunnels.io/crm/post-workflow#crm-functions-reference'), 'CRM reference');
    assert.match(s, /ef <cmd> --help/, 'points at per-command help');
    assert.match(s, /Never assume a capability is missing/i, 'the do-not-guess rule');
});

test('guidance states the two form/collection traps that silently lose leads', () => {
    const s = renderClaudeSection();
    assert.match(s, /no \*\*`action` attribute\*\*|no `action`/, 'writing an action opts the form out');
    assert.match(s, /skipped when the page contains backend template syntax/i, 'the {{ }} exclusion');
    assert.match(s, /re-read the file before editing it again/i, 'push rewrites the local file');
});

test('the managed block is stamped with the CLI version so it can be refreshed later', () => {
    const s = renderClaudeSection();
    assert.match(s, /<!-- ef:begin v\d+\.\d+\.\d+ \(generated by `ef claude`/, 'begin marker carries a version');
    assert.equal(stampedGuidanceVersion(s), guidanceVersion());
});

test('applyAgentGuidance creates, then updates in place (idempotent — no duplicate block)', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-claude-'));
    const target = path.join(dir, 'CLAUDE.md');
    try {
        assert.equal(await applyAgentGuidance(target), 'created');
        const first = await fs.promises.readFile(target, 'utf8');
        assert.equal(await applyAgentGuidance(target), 'updated');
        const second = await fs.promises.readFile(target, 'utf8');
        assert.equal(second, first, 'idempotent re-run produces identical content');
        assert.equal(second.match(/ef:begin/g)?.length, 1, 'exactly one managed block');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('installBundledSkills writes ef-page-events into .claude/skills/ with valid frontmatter', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-skills-'));
    try {
        const installed = await installBundledSkills(dir);
        assert.ok(installed.includes('ef-page-events'), `expected the ef-page-events skill; got ${JSON.stringify(installed)}`);
        const skillFile = path.join(dir, '.claude', 'skills', 'ef-page-events', 'SKILL.md');
        assert.ok(fs.existsSync(skillFile), 'SKILL.md written under .claude/skills/');
        const body = await fs.promises.readFile(skillFile, 'utf8');
        assert.ok(body.startsWith('---\n'), 'opens with YAML frontmatter');
        assert.match(body, /\nname: ef-page-events\b/, 'frontmatter carries the skill name');
        assert.match(body, /description:/, 'has a description for on-demand loading');
        // The load-bearing correctness content must be present.
        assert.match(body, /always pull first/i);
        assert.match(body, /page_variant/, 'LOAD-vs-REDIRECT guidance');
        assert.match(body, /compiled `script_rule`|script_rule/, 'the typed-condition trap');
        // Idempotent overwrite.
        assert.deepEqual(await installBundledSkills(dir), installed, 're-run installs the same set');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('applyAgentGuidance appends to an existing CLAUDE.md without clobbering it', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-claude-'));
    const target = path.join(dir, 'CLAUDE.md');
    try {
        await fs.promises.writeFile(target, '# My project\n\nExisting notes.\n');
        assert.equal(await applyAgentGuidance(target), 'appended');
        const out = await fs.promises.readFile(target, 'utf8');
        assert.ok(out.includes('# My project'), 'keeps existing content');
        assert.ok(out.includes('Existing notes.'));
        assert.ok(out.includes('ef:begin'), 'adds the managed block');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('the ef-stats skill ships, and carries the interpretation traps that make it worth having', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-skills-stats-'));
    try {
        const installed = await installBundledSkills(dir);
        assert.ok(installed.includes('ef-stats'), `expected the ef-stats skill; got ${JSON.stringify(installed)}`);
        const body = await fs.promises.readFile(path.join(dir, '.claude', 'skills', 'ef-stats', 'SKILL.md'), 'utf8');
        assert.ok(body.startsWith('---\n'), 'opens with YAML frontmatter');
        assert.match(body, /\nname: ef-stats\b/);
        // The flags are in --help. These four are the reasons the skill exists:
        // each one produces a confidently wrong answer with nothing in the
        // output to warn the reader.
        assert.match(body, /America\/Los_Angeles/, 'the timezone fallback trap');
        assert.match(body, /unavailable/i, 'a missing metric is not zero');
        assert.match(body, /did not ask for|not request/i, 'resolver extras');
        assert.match(body, /[Nn]ever recompute/, 'significance is read, not derived');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('guidance routes performance questions to ef stats', () => {
    // Without a row in the task table an agent has no way to discover the
    // command exists, and will answer analytics questions by guessing.
    const text = renderClaudeSection();
    assert.match(text, /ef stats/, 'the command is named');
    assert.match(text, /analyticsTz|--tz/, 'the timezone rule travels with it');
    assert.match(text, /ef stats metrics/, 'metric keys are per-brand and must be discovered');
});

test('ef cursor writes a .mdc rule whose frontmatter survives a re-run', async () => {
    // Cursor needs YAML frontmatter to know when a rule applies. It is written
    // once, on create — a user who narrows the rule (globs, alwaysApply:false)
    // must keep that edit when the managed block is later refreshed.
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-cursor-'));
    try {
        const target = path.join(dir, GUIDANCE_FILES.cursor);
        assert.equal(await applyAgentGuidance(target, { frontmatter: CURSOR_FRONTMATTER }), 'created');

        const created = await fs.promises.readFile(target, 'utf8');
        assert.ok(created.startsWith('---\n'), 'opens with Cursor frontmatter');
        assert.match(created, /alwaysApply: true/);

        await fs.promises.writeFile(target, created.replace('alwaysApply: true', 'alwaysApply: false'));
        assert.equal(await applyAgentGuidance(target, { frontmatter: CURSOR_FRONTMATTER }), 'updated');

        const after = await fs.promises.readFile(target, 'utf8');
        assert.match(after, /alwaysApply: false/, 'the user edit is preserved, not reset');
        assert.equal(after.match(/ef:begin/g)?.length, 1, 'no duplicate managed block');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('guidance warns that ef watch is long-running and not for an agent to start', () => {
    // An agent that runs `ef watch` hangs its own turn on a process behaving
    // exactly as designed, with no error to notice. The bullet alone was not
    // enough — the task table is what gets scanned when picking a command.
    const text = renderClaudeSection();
    assert.match(text, /\| Ship every save automatically \|/, 'ef watch has a task-table row');
    assert.match(text, /never start it from an agent/i);
    assert.match(text, /an agent should not start it/i);
});

test('ef status names the missing guidance, and stays quiet once it is declined', async () => {
    const dir = await fs.promises.realpath(await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-nudge-')));
    const server = http.createServer((_req, res) => {
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end('[]');
    });
    await new Promise<void>((r) => server.listen(0, '127.0.0.1', () => r()));
    const port = (server.address() as { port: number }).port;
    const cfg = path.join(dir, '.ef', 'config.json');
    const run = (): Promise<string> => new Promise((resolve) => {
        const child = spawn(process.execPath, [BIN_PATH, 'status'], { cwd: dir, env: { ...process.env, NO_COLOR: '1' } });
        let err = '';
        child.stderr.on('data', (d) => (err += d));
        child.stdout.on('data', () => {});
        child.on('close', () => resolve(err));
    });
    try {
        await fs.promises.mkdir(path.join(dir, '.ef'), { recursive: true });
        const base = { apiUrl: `http://127.0.0.1:${port}`, brandId: 7, syncRoot: 'elasticfunnels', syncLayout: 'flat', saveMode: 'direct' };
        await fs.promises.writeFile(cfg, JSON.stringify(base));
        await fs.promises.writeFile(path.join(dir, '.ef', 'auth'), 'k\n');

        assert.match(await run(), /No AI guidance here/, 'an old project is told what it is missing');

        // A recorded refusal must silence it — the point of storing the choice.
        await fs.promises.writeFile(cfg, JSON.stringify({ ...base, aiGuidance: false }));
        assert.doesNotMatch(await run(), /No AI guidance here/, 'a declined project is not nagged');
    } finally {
        await new Promise<void>((r) => server.close(() => r()));
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('guidance and skills agree on where a split test\'s intent is recorded', () => {
    // A test\'s numbers are on the server; the hypothesis and which arm is the
    // control exist only in the conversation that created it. If the creating
    // skill and the reading skill disagree about the filename, the record is
    // written where nothing looks for it.
    const guide = renderClaudeSection();
    assert.match(guide, /elasticfunnels\/split-tests\.md/);

    const root = path.resolve(__dirname, '..', '..', 'assets', 'skills');
    const events = fs.readFileSync(path.join(root, 'ef-page-events', 'SKILL.md'), 'utf8');
    const stats = fs.readFileSync(path.join(root, 'ef-stats', 'SKILL.md'), 'utf8');

    assert.match(events, /elasticfunnels\/split-tests\.md/, 'the skill that creates tests writes the record');
    assert.match(stats, /elasticfunnels\/split-tests\.md/, 'the skill that reads tests consults it');
    assert.match(events, /[Aa]ppend, never rewrite|append-only/, 'losing tests stay in the history');
    assert.match(events, /split test id/i, 'the id is the join key, since slugs get renamed');
});

test('guidance tells the agent to check the CLI version but not to install it', () => {
    // Two halves, and both matter. The notifier suppresses itself whenever
    // stderr is not a TTY — always true for an agent — so without being told,
    // an agent never learns the CLI is stale and quietly follows guidance for a
    // version it is not running. But `ef update` is a GLOBAL install: it
    // changes a binary shared with every other project on the machine, can need
    // sudo, and swaps the tool mid-task. Check, report, let the human decide.
    const text = renderClaudeSection();
    assert.match(text, /ef update --check/, 'the read-only check is named');
    assert.match(text, /[Dd]o not run `ef update` yourself/, 'installing is off-limits');
    assert.match(text, /global install/i, 'and the reason why is given');
});

test('guidance teaches wildcard routes, and to prefer them over ?id= query strings', () => {
    const s = renderClaudeSection();
    assert.match(s, /Wildcard routes/, 'the section exists');
    assert.match(s, /instead of `\?id=`\/`\?code=`/, 'steers away from query-string detail pages');
    assert.match(s, /route_params/, 'names the template variable');
    assert.match(s, /there is no `segment_0`/, 'kills the segment_0 myth the old docs carried');
    assert.match(s, /Placeholders must all be trailing/, 'the prefix-stops-at-first-brace limit');
    assert.match(s, /can never \*start\* with a placeholder/, 'leading placeholders never match');
    assert.ok(s.includes('https://docs.elasticfunnels.io/pages/wildcard-routes'), 'links the docs page');
});

/*
 * The SessionStart hook had no coverage at all, and it just grew a second
 * command. The interesting case is not the fresh project — it is the project
 * set up by an older CLI, which already carries the pull command. Re-running
 * `ef claude` there has to add the update check WITHOUT installing a second
 * copy of the pull, or every upgrade doubles the hook.
 */
test('the session hook installs both commands, and tops up an older pull-only hook', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-hook-'));
    const settingsPath = path.join(dir, '.claude', 'settings.json');
    const commandsIn = (s: any): string[] =>
        (s.hooks.SessionStart as any[]).flatMap((e) => (e.hooks as any[]).map((h) => h.command));

    // Fresh project: both commands, and nothing else invented.
    assert.equal(await installSessionHook(dir), 'created');
    let settings = JSON.parse(await fs.promises.readFile(settingsPath, 'utf8'));
    assert.deepEqual(commandsIn(settings), ['ef pull --if-stale 30', 'ef update --cached']);

    // Re-run is a no-op, not a second copy.
    assert.equal(await installSessionHook(dir), 'present');
    settings = JSON.parse(await fs.promises.readFile(settingsPath, 'utf8'));
    assert.deepEqual(commandsIn(settings), ['ef pull --if-stale 30', 'ef update --cached']);

    // A project written by <= 0.18.0: pull only, plus a hand-written hook of
    // the user's that must survive untouched.
    const legacy = path.join(dir, 'legacy');
    await fs.promises.mkdir(path.join(legacy, '.claude'), { recursive: true });
    await fs.promises.writeFile(path.join(legacy, '.claude', 'settings.json'), JSON.stringify({
        hooks: { SessionStart: [{ hooks: [{ type: 'command', command: 'ef pull --if-stale 30' }] }] },
        permissions: { allow: ['Bash(ef:*)'] },
    }));
    assert.equal(await installSessionHook(legacy), 'added');
    const upgraded = JSON.parse(await fs.promises.readFile(path.join(legacy, '.claude', 'settings.json'), 'utf8'));
    assert.deepEqual(commandsIn(upgraded), ['ef pull --if-stale 30', 'ef update --cached'], 'gains only what it lacked');
    assert.deepEqual(upgraded.permissions, { allow: ['Bash(ef:*)'] }, 'unrelated settings survive');

    await fs.promises.rm(dir, { recursive: true, force: true });
});

/*
 * `--cached` exists so the hook cannot put a registry round-trip in front of
 * every session. Two properties matter: it must never block on the network,
 * and it must stay SILENT when the CLI is current — a hook that prints every
 * session is a hook people delete.
 */
test('ef update --cached answers from the cache, never the network, and is quiet when current', async () => {
    const home = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-home-'));
    const cacheDir = path.join(home, '.config', 'elasticfunnels');
    await fs.promises.mkdir(cacheDir, { recursive: true });
    const cacheFile = path.join(cacheDir, 'update-check.json');

    const run = (): Promise<{ out: string; code: number | null }> => new Promise((resolve) => {
        const child = spawn(process.execPath, [BIN_PATH, 'update', '--cached', '--json'], {
            // A bogus registry host: if --cached ever reaches for the network,
            // this test hangs or fails instead of quietly passing.
            env: { ...process.env, HOME: home, USERPROFILE: home, NO_COLOR: '1', npm_config_registry: 'http://127.0.0.1:1' },
        });
        let out = '';
        child.stdout.on('data', (d) => (out += d));
        child.stderr.on('data', () => {});
        child.on('close', (code) => resolve({ out, code }));
    });

    // A cache claiming a far-future release → an update is reported.
    await fs.promises.writeFile(cacheFile, JSON.stringify({ latest: '999.0.0', checkedAt: Date.now() }));
    let res = await run();
    assert.equal(res.code, 0, 'a hook must never fail the session');
    assert.equal(JSON.parse(res.out).updateAvailable, true);
    assert.equal(JSON.parse(res.out).source, 'cache', 'answered from the cache, not the registry');

    // A cache at or behind the running version → nothing to say.
    await fs.promises.writeFile(cacheFile, JSON.stringify({ latest: '0.0.1', checkedAt: Date.now() }));
    res = await run();
    assert.equal(res.code, 0);
    assert.equal(JSON.parse(res.out).updateAvailable, false);

    // Cold cache: "unknown", not a fabricated "up to date".
    await fs.promises.rm(cacheFile, { force: true });
    res = await run();
    assert.equal(res.code, 0, 'a cold cache is not an error');
    assert.equal(JSON.parse(res.out).latest, null, 'says unknown rather than guessing');

    await fs.promises.rm(home, { recursive: true, force: true });
});
