import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { renderClaudeSection, applyAgentGuidance, installBundledSkills, stampedGuidanceVersion, guidanceVersion, GUIDANCE_FILES, CURSOR_FRONTMATTER } from '../src/commands/claude';

test('renderClaudeSection ports the .cursor template/backend-script/CRM docs', () => {
    const s = renderClaudeSection();
    for (const needle of ["asset('/main.css')", '@foreach(', '@component(', '@extends(', '<template-if', '[[ expression ]]', 'CRM functions', 'COLLECTION_CODE', 'saveMode', 'efmeta']) {
        assert.ok(s.includes(needle), `guidance should mention ${needle}`);
    }
});

/*
 * This locks in the fact that cost a live page. The CRM functions are
 * registered TWICE with different casing — PascalCase in the template engine
 * (CrmAdapter), camelCase in the backend-script runtime (BackendCodeService) —
 * and the sets are not identical. An agent called `CreateCrmEntry` (template
 * only) inside a backend script; the undefined function broke the render and
 * the domain served 404 until it was rolled back.
 */
test('guidance splits CRM functions by runtime instead of picking one casing', () => {
    const s = renderClaudeSection();

    // Both real sets must be present, with their own casing.
    for (const template of ['CreateCrmEntry', 'SetCrmRelation', 'EnsureCrmEntity']) {
        assert.ok(s.includes(template), `template-engine function ${template} must be listed`);
    }
    for (const script of ['setCrmFields', 'addCrmFieldValue', 'reassignCrmReference', 'ensureCrmEntity']) {
        assert.ok(s.includes(script), `backend-script function ${script} must be listed`);
    }

    // The trap itself, stated explicitly.
    assert.match(s, /not interchangeable/i, 'says the two sets cannot be swapped');
    assert.match(s, /only in templates/i, 'marks the template-only functions');
    assert.match(s, /only in backend scripts/i, 'marks the script-only functions');
    assert.ok(s.includes('there is no `createCrmEntry`'), 'states that the camelCase spelling does not exist');
    assert.match(s, /404/, 'says what actually happens when the name is wrong');
});

test('guidance links the authoritative docs and tells the agent to run --help', () => {
    const s = renderClaudeSection();
    assert.ok(s.includes('https://docs.elasticfunnels.io/backend-scripts/data-functions'), 'data-functions reference');
    assert.ok(s.includes('https://docs.elasticfunnels.io/crm/post-workflow#crm-functions-reference'), 'CRM reference');
    assert.match(s, /ef <cmd> --help/, 'points at per-command help');
    assert.match(s, /Never assume a capability is missing/i, 'the do-not-guess rule');
});

test('guidance states the two form/collection traps that silently lose leads', () => {
    const s = renderClaudeSection();
    assert.match(s, /no \*\*`action` attribute\*\*|no `action`/, 'writing an action opts the form out');
    assert.match(s, /skipped when the page contains backend template syntax/i, 'the {{ }} exclusion');
    assert.match(s, /re-read the file before editing it again/i, 'push rewrites the local file');
});

test('the managed block is stamped with the CLI version so it can be refreshed later', () => {
    const s = renderClaudeSection();
    assert.match(s, /<!-- ef:begin v\d+\.\d+\.\d+ \(generated by `ef claude`/, 'begin marker carries a version');
    assert.equal(stampedGuidanceVersion(s), guidanceVersion());
});

test('applyAgentGuidance creates, then updates in place (idempotent — no duplicate block)', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-claude-'));
    const target = path.join(dir, 'CLAUDE.md');
    try {
        assert.equal(await applyAgentGuidance(target), 'created');
        const first = await fs.promises.readFile(target, 'utf8');
        assert.equal(await applyAgentGuidance(target), 'updated');
        const second = await fs.promises.readFile(target, 'utf8');
        assert.equal(second, first, 'idempotent re-run produces identical content');
        assert.equal(second.match(/ef:begin/g)?.length, 1, 'exactly one managed block');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('installBundledSkills writes ef-page-events into .claude/skills/ with valid frontmatter', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-skills-'));
    try {
        const installed = await installBundledSkills(dir);
        assert.ok(installed.includes('ef-page-events'), `expected the ef-page-events skill; got ${JSON.stringify(installed)}`);
        const skillFile = path.join(dir, '.claude', 'skills', 'ef-page-events', 'SKILL.md');
        assert.ok(fs.existsSync(skillFile), 'SKILL.md written under .claude/skills/');
        const body = await fs.promises.readFile(skillFile, 'utf8');
        assert.ok(body.startsWith('---\n'), 'opens with YAML frontmatter');
        assert.match(body, /\nname: ef-page-events\b/, 'frontmatter carries the skill name');
        assert.match(body, /description:/, 'has a description for on-demand loading');
        // The load-bearing correctness content must be present.
        assert.match(body, /always pull first/i);
        assert.match(body, /page_variant/, 'LOAD-vs-REDIRECT guidance');
        assert.match(body, /compiled `script_rule`|script_rule/, 'the typed-condition trap');
        // Idempotent overwrite.
        assert.deepEqual(await installBundledSkills(dir), installed, 're-run installs the same set');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('applyAgentGuidance appends to an existing CLAUDE.md without clobbering it', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-claude-'));
    const target = path.join(dir, 'CLAUDE.md');
    try {
        await fs.promises.writeFile(target, '# My project\n\nExisting notes.\n');
        assert.equal(await applyAgentGuidance(target), 'appended');
        const out = await fs.promises.readFile(target, 'utf8');
        assert.ok(out.includes('# My project'), 'keeps existing content');
        assert.ok(out.includes('Existing notes.'));
        assert.ok(out.includes('ef:begin'), 'adds the managed block');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('the ef-stats skill ships, and carries the interpretation traps that make it worth having', async () => {
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-skills-stats-'));
    try {
        const installed = await installBundledSkills(dir);
        assert.ok(installed.includes('ef-stats'), `expected the ef-stats skill; got ${JSON.stringify(installed)}`);
        const body = await fs.promises.readFile(path.join(dir, '.claude', 'skills', 'ef-stats', 'SKILL.md'), 'utf8');
        assert.ok(body.startsWith('---\n'), 'opens with YAML frontmatter');
        assert.match(body, /\nname: ef-stats\b/);
        // The flags are in --help. These four are the reasons the skill exists:
        // each one produces a confidently wrong answer with nothing in the
        // output to warn the reader.
        assert.match(body, /America\/Los_Angeles/, 'the timezone fallback trap');
        assert.match(body, /unavailable/i, 'a missing metric is not zero');
        assert.match(body, /did not ask for|not request/i, 'resolver extras');
        assert.match(body, /[Nn]ever recompute/, 'significance is read, not derived');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('guidance routes performance questions to ef stats', () => {
    // Without a row in the task table an agent has no way to discover the
    // command exists, and will answer analytics questions by guessing.
    const text = renderClaudeSection();
    assert.match(text, /ef stats/, 'the command is named');
    assert.match(text, /analyticsTz|--tz/, 'the timezone rule travels with it');
    assert.match(text, /ef stats metrics/, 'metric keys are per-brand and must be discovered');
});

test('ef cursor writes a .mdc rule whose frontmatter survives a re-run', async () => {
    // Cursor needs YAML frontmatter to know when a rule applies. It is written
    // once, on create — a user who narrows the rule (globs, alwaysApply:false)
    // must keep that edit when the managed block is later refreshed.
    const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'ef-cli-cursor-'));
    try {
        const target = path.join(dir, GUIDANCE_FILES.cursor);
        assert.equal(await applyAgentGuidance(target, { frontmatter: CURSOR_FRONTMATTER }), 'created');

        const created = await fs.promises.readFile(target, 'utf8');
        assert.ok(created.startsWith('---\n'), 'opens with Cursor frontmatter');
        assert.match(created, /alwaysApply: true/);

        await fs.promises.writeFile(target, created.replace('alwaysApply: true', 'alwaysApply: false'));
        assert.equal(await applyAgentGuidance(target, { frontmatter: CURSOR_FRONTMATTER }), 'updated');

        const after = await fs.promises.readFile(target, 'utf8');
        assert.match(after, /alwaysApply: false/, 'the user edit is preserved, not reset');
        assert.equal(after.match(/ef:begin/g)?.length, 1, 'no duplicate managed block');
    } finally {
        await fs.promises.rm(dir, { recursive: true, force: true });
    }
});

test('guidance warns that ef watch is long-running and not for an agent to start', () => {
    // An agent that runs `ef watch` hangs its own turn on a process behaving
    // exactly as designed, with no error to notice. The bullet alone was not
    // enough — the task table is what gets scanned when picking a command.
    const text = renderClaudeSection();
    assert.match(text, /\| Ship every save automatically \|/, 'ef watch has a task-table row');
    assert.match(text, /never start it from an agent/i);
    assert.match(text, /an agent should not start it/i);
});
