import * as path from 'path';
import * as fs from 'fs';
import { Command } from 'commander';
import { log } from '../utils/log';
import { findProjectRoot } from '../utils/store';
import { writeFileAtomic } from '../utils/fs';

/**
 * `ef claude` — drop ElasticFunnels guidance into CLAUDE.md so Claude Code
 * knows how to work with the synced `elasticfunnels/` tree. The Claude-native
 * equivalent of the VS Code extension's `.cursor/rules/*.mdc`.
 *
 * Idempotent: the guidance is written between markers, so re-running updates
 * that block in place and never disturbs the rest of an existing CLAUDE.md.
 * `applyClaudeGuidance` is reused by `ef init` so a fresh project gets it too.
 */

const BEGIN = '<!-- ef:begin (generated by `ef claude` — safe to re-run) -->';
const END = '<!-- ef:end -->';

const GUIDE = `# ElasticFunnels project

This project's \`elasticfunnels/\` folder is **synced with the ElasticFunnels
server** by the \`ef\` CLI. Files here represent live server-side entities — edit
them locally, then push.

## Folder layout (flat)

\`\`\`
elasticfunnels/
  pages/          .ef page files (subdirectories = nested slugs / variants)
  components/     .ef reusable component files
  scripts/        .js standalone backend scripts
  assets/         JS/CSS/media synced from the server
  variables.json  brand variables (editable — syncs on push)
  .ef-state.json  internal sync state — DO NOT EDIT
  .ef-state/      internal snapshot cache — DO NOT EDIT
\`\`\`

The brand id lives in \`.ef/config.json\`, not in the path.

## CRITICAL: the \`efmeta\` line — NEVER touch it

The **first line** of every synced \`.ef\` file is machine identity — a
\`{{-- efmeta:{...} --}}\` comment (backend \`.js\` scripts use \`// efmeta:{...}\`)
carrying the server \`id\`/\`type\`/\`brandId\`/\`slug\`/\`path\`. It is **path-bound**.

**Rule with NO exceptions: never add, edit, remove, reformat, reorder, or "fix"
the efmeta line, for ANY reason** — not to correct a slug, not to tidy the JSON,
not while resolving a merge. Only ever change the body **below** it.

- The CLI **REJECTS \`ef push\`** (exit 4, conflict) for a file whose efmeta no
  longer matches its tracked identity in \`.ef-state.json\`. If you hit that, run
  \`ef pull <path>\` to restore the correct line — do **not** hand-edit it back.
- **Never write or paste an efmeta line** into code you generate. The CLI stamps
  the correct one on pull/push. (It intentionally holds only stable identity —
  no title, no revision number — so it rarely changes.)
- **When duplicating a page/component**, copy the **body only** — strip the first
  line if it begins with \`{{-- efmeta:\` or \`// efmeta:\`. Otherwise the copy
  inherits the original's identity and can overwrite the wrong server entity.
- The \`{{-- --}}\` comment is stripped at render time and never reaches the browser.

## Do not touch

- \`.ef-state.json\` and \`.ef-state/\` — the CLI manages these (path↔id mapping,
  content hashes, conflict snapshots). Editing them corrupts drift detection.

## \`.ef\` template syntax

\`.ef\` files are HTML with ElasticFunnels' template engine, in **two layers**:

- **Backend** — rendered on the server (and in preview). Use \`@if\`, \`@foreach\`,
  \`{{ ... }}\`. For content fixed at render time (device, query params, brand
  vars, orders, products).
- **Frontend** — runs in the browser, reactive via \`window.efScope\`. Use
  \`<template-if>\`, \`[[ ... ]]\`. For content that must react to client state
  (cart, toggles, form state).

**Match the patterns in the existing \`.ef\` files in this project** — don't
invent directives.

### Backend (server-rendered)

- **Output:** \`{{ var }}\`, \`{{ path.to.value }}\`, \`{{ query.utm_source }}\`
- **Filters** (chain with \`|\`; args via \`:\`): \`{{ name | upper }}\`,
  \`{{ text | truncate:80 }}\`, \`{{ x | default:'Offer' }}\`. Common ones: \`raw\`
  (output HTML unescaped), \`default\`, \`slice\`, \`date\` (e.g. \`date:'dd MMM yyyy'\`),
  \`currency\`, \`number_format\`, \`truncate\`/\`truncatewords\`, \`upper\`/\`lower\`/\`capitalize\`/\`title\`,
  \`json\`, \`timeago\`, \`yesno\`, \`replace\`, \`strip_tags\`, \`length\`, \`first\`/\`last\`,
  \`join\`, \`sort\`, \`round\`.
- **Conditionals:** \`@if(cond) … @elseif(cond) … @else … @endif\`. Operators (word
  form): \`eq neq lt lte gt gte\`; logic \`and\` \`or\`; unary \`!\`. e.g.
  \`@if(orders.length gt 0)\`.
- **Loops:** \`@foreach(item in array) … @endforeach\`.
- **Set a variable:** \`@set(name = expression)\`.
- **Components:** \`@component("component-code", { title: "Home", items: list })\` —
  include a component by its code; args are an object.
- **Inheritance:** \`@extends("wrapper-slug")\`, then \`@block("name") … @endblock\`
  (block name must match the base's \`@block("name")\`).
- **Functions** \`{{ fn(...) }}\`: **\`asset('/main.css')\`** → the brand CDN URL (use
  this for every local asset reference, not a bare path); \`buy('product-code')\`,
  \`upsell(...)\`, \`downsell(...)\`, \`decline(...)\` → purchase links; \`getProduct(s)\`,
  \`getOrders\`, \`getOrder\`, \`getCustomer\`, \`getCourse(s)\`, \`getBlog(s)\`,
  \`getSubscription(s)\`; \`date(...)\`, \`t('key')\` / \`getTranslation\`, \`getBrand\`,
  \`get/setSessionItem\`, \`dump(x)\`. (The full set is large — check existing files.)
- **CRM helpers** (templates + backend scripts): \`CreateCrmEntry\`, \`SetCrmField(s)\`,
  \`GetCrmEntries\`, \`GetCrmField(s)\`, \`MoveCrmToStage\`/\`MoveCrmToPipeline\`,
  \`SetCrmRelation\`, … — create/update CRM leads and their fields.
- **Context** available in \`@if\`/\`{{ }}\`: \`var.*\` (brand variables, e.g.
  \`{{ var.offer_name }}\`); \`request.is_mobile\`/\`is_tablet\`/\`is_customer\`/\`referer\`/\`merchant_code\`;
  \`query.*\` (URL params); \`page\`; \`orders\` (customer orders, newest first; empty
  when no customer).

### Frontend (browser, reactive)

Data lives in \`window.efScope\`; mutate it and call \`notifyScopeUpdated()\` (or fire
\`ef-scope-updated\`) to re-render.

- **Output:** \`[[ expression ]]\` — frontend uses \`[[ ]]\`; backend uses \`{{ }}\`.
- **Condition:** \`<template-if data-condition="cartCount > 0"> … <template-else> … </template-if>\`
  (always \`data-condition\`).
- **Loop:** \`<template-foreach data-each="item in items"> … </template-foreach>\`.
- **Vars scope:** \`<template-vars> … [[ var.name ]] … </template-vars>\`;
  **set:** \`<template-set data-variable="x" data-value="expr">\`;
  **component:** \`<template-component data-component-name="x" data-args='{"k":"v"}'>\`.
- **Bindings:** \`data-ef-text="expr"\`, \`data-ef-html="expr"\` (trusted),
  \`@click="expr"\` / \`data-ef-on:click\`, one-way \`:attr="expr"\`
  (\`:value\`/\`:checked\`/\`:disabled\`/\`:style\`), two-way \`data-template-value="path"\`
  (v-model for inputs/selects/textareas).

## Forms → collections

Write a normal \`<form>\` with \`name\`d inputs. On push/save the backend
**auto-creates a collection** and rewrites the form's \`action\` +
\`data-collection\`/\`data-collection-id\` attributes. **Don't invent collection
codes** — let the backend generate them. (Optional: use the literal
\`COLLECTION_CODE\` placeholder to name or link one explicitly.)

## Page variants (A/B tests)

Variants of a page live under a subfolder named after the base slug:
\`pages/my-page/my-page.ef\` (active — holds the main \`slug\`) plus
\`pages/my-page/my-page-v2.ef\` (variant — uses \`variant_slug\`). Single pages sit
directly under \`pages/\`. Change a slug with \`ef pages settings <slug> --slug <new>\`
(the CLI renames the local file to match).

## Backend scripts

Standalone scripts in \`elasticfunnels/scripts/*.js\` run **server-side** on page
requests. The first line is a \`// efmeta:{...}\` identity comment (same rules —
never write or copy it).

- **Globals (read-only):** request/query/customer/order context.
- **Actions (side effects):** session & cookies, \`redirect(url)\` (stops
  rendering), set template variables, custom response, response headers.
- **Data functions:** the same helpers as templates — \`getCustomer\`, \`getOrders\`,
  \`getProduct(s)\`, courses, blog, purchase links (\`buy\`/\`upsell\`),
  \`asset('/main.css')\`, CRM functions.
- **HTTP:** can call external APIs. **Cross-file imports:** a script can import
  other backend-script modules.
- Manage with the CLI: \`ef scripts list | pull <codeOrId> | push <pathOrCode> | create <code> | delete <codeOrId>\`.
- Docs: https://docs.elasticfunnels.io/backend-scripts/overview

## Working with the \`ef\` CLI

Run from anywhere inside the project (the CLI walks up to find \`.ef/\`):

- \`ef status\` — connection, last sync, entity counts.
- \`ef pull\` — pull everything. \`ef pull pages/about.ef\` for one file.
- \`ef diff\` — show local-vs-server drift before pushing. Run this first.
- \`ef push pages/about.ef\` — push a file (optimistic concurrency). \`--all\` for
  everything, \`--dry-run\` to preview, \`--force\` to override a conflict.
- \`ef pages push <slugOrPath>\` · \`ef components push <codeOrPath>\` ·
  \`ef scripts push <pathOrCode>\` — push one entity by path or code.
- \`ef components create <code>\` · \`ef pages create <slug>\` — create an entity.
- \`ef config get\` / \`ef config set saveMode direct\` — view/change project config.
- \`ef preview <slug>\` — editor preview URL.
- \`ef list pages --json\` — machine-readable listings (every command takes
  \`--json\`; output goes to stdout, logs to stderr, so piping is safe).

### Save modes (draft vs direct)

\`ef push\` **publishes** by default (\`saveMode: direct\`). Pass \`--draft\` to save a
draft that isn't live until published; \`--direct\` forces a publish. A draft push
prints a warning that it's not live. Change the project default with
\`ef config set saveMode draft|direct\`.

### Safe edit loop

1. \`ef pull\` (or \`ef diff\` to check you're current).
2. Edit \`.ef\` files — **never** the \`efmeta\` line or \`.ef-state.json\`.
3. \`ef diff\` to review what changed.
4. \`ef push <paths…>\`. On an HTTP 409 conflict (exit 4): \`ef pull <path>\`,
   re-apply your change, push again.

Exit codes: 0 ok · 2 usage · 3 auth · 4 conflict · 5 network · 6 server · 7 not found.`;

/** The marked, ready-to-embed guidance block. */
export function renderClaudeSection(): string {
    return `${BEGIN}\n\n${GUIDE.trim()}\n\n${END}`;
}

/**
 * Write / refresh the ElasticFunnels guidance block in `target` (a CLAUDE.md
 * path). Idempotent: replaces the managed block in place, appends it to an
 * existing file, or creates the file. Returns what it did. Reused by `ef init`.
 */
export async function applyClaudeGuidance(target: string): Promise<'created' | 'updated' | 'appended'> {
    const section = renderClaudeSection();
    let existing = '';
    try { existing = await fs.promises.readFile(target, 'utf8'); } catch { /* new file */ }

    let next: string;
    let action: 'created' | 'updated' | 'appended';
    if (existing.includes(BEGIN) && existing.includes(END)) {
        const before = existing.slice(0, existing.indexOf(BEGIN));
        const after = existing.slice(existing.indexOf(END) + END.length);
        next = `${before}${section}${after}`;
        action = 'updated';
    } else if (existing.trim()) {
        next = `${existing.replace(/\s*$/, '')}\n\n${section}\n`;
        action = 'appended';
    } else {
        next = `${section}\n`;
        action = 'created';
    }
    await writeFileAtomic(target, next);
    return action;
}

export function registerClaudeCommand(program: Command): void {
    program
        .command('claude')
        .description('Write ElasticFunnels guidance for Claude Code into CLAUDE.md (idempotent — safe to re-run).')
        .option('--output <path>', 'Target file (default: CLAUDE.md in the project root).')
        .option('--print', 'Print the guidance to stdout instead of writing a file.')
        .action(async (opts: { output?: string; print?: boolean }) => {
            if (opts.print) {
                process.stdout.write(renderClaudeSection() + '\n');
                return;
            }
            const root = findProjectRoot() ?? process.cwd();
            const target = opts.output ? path.resolve(opts.output) : path.join(root, 'CLAUDE.md');
            const action = await applyClaudeGuidance(target);
            const verb = action === 'created' ? 'Created' : action === 'updated' ? 'Updated ElasticFunnels section in' : 'Appended ElasticFunnels section to';
            log.success(`${verb} ${target}`);
        });
}
