import * as path from 'path';
import * as fs from 'fs';
import { Command } from 'commander';
import { log } from '../utils/log';
import { findProjectRoot } from '../utils/store';
import { writeFileAtomic } from '../utils/fs';

/**
 * `ef claude` — drop ElasticFunnels guidance into CLAUDE.md so Claude Code
 * knows how to work with the synced `elasticfunnels/` tree. The Claude-native
 * equivalent of the VS Code extension's `.cursor/rules/*.mdc`.
 *
 * Idempotent: the guidance is written between markers, so re-running updates
 * that block in place and never disturbs the rest of an existing CLAUDE.md.
 */

const BEGIN = '<!-- ef:begin (generated by `ef claude` — safe to re-run) -->';
const END = '<!-- ef:end -->';

const GUIDE = `# ElasticFunnels project

This project's \`elasticfunnels/\` folder is **synced with the ElasticFunnels
server** by the \`ef\` CLI. Files here represent live server-side entities — edit
them locally, then push.

## Folder layout (flat)

\`\`\`
elasticfunnels/
  pages/          .ef page files (subdirectories = nested slugs)
  components/     .ef reusable component files
  scripts/        .js standalone backend scripts
  assets/         JS/CSS/media synced from the server
  variables.json  brand variables (editable — syncs on push)
  .ef-state.json  internal sync state — DO NOT EDIT
  .ef-state/      internal snapshot cache — DO NOT EDIT
\`\`\`

The brand id lives in \`.ef/config.json\`, not in the path.

## CRITICAL: the \`efmeta\` line

Every synced \`.ef\` file starts with a \`{{-- efmeta:{...} --}}\` comment (backend
\`.js\` scripts use \`// efmeta:{...}\`). It carries the server id, type, brand, and
the path the file was issued for, and is **path-bound**.

- **Never write, paste, or copy an \`efmeta\` line** into code you generate. The
  CLI injects the correct, path-bound metadata on push.
- **When duplicating a page/component**, copy the **body only** — strip the
  first line if it begins with \`{{-- efmeta:\` or \`// efmeta:\`. Otherwise the new
  file inherits the original's identity and deleting either one can destroy the
  wrong server entity.
- **Never edit** the \`path\`, \`id\`, \`brandId\`, or \`type\` fields of an existing
  \`efmeta\` block. If you must remove it, delete the **entire** first line.
- The \`{{-- --}}\` comment is stripped at render time and never reaches the
  browser.

## Do not touch

- \`.ef-state.json\` and \`.ef-state/\` — the CLI manages these (path↔id mapping,
  content hashes, conflict snapshots). Editing them corrupts drift detection.

## Template engine

\`.ef\` files use ElasticFunnels' template engine. \`{{ ... }}\` emits values;
\`{{-- ... --}}\` is a comment stripped at render. **Match the patterns in the
existing \`.ef\` files in this project** rather than inventing directives — and
when unsure, check the official docs:

- Overview: https://docs.elasticfunnels.io/
- Frontend template engine: https://docs.elasticfunnels.io/frontend-template-engine/overview
- Backend template engine: https://docs.elasticfunnels.io/backend-template-engine/overview

## Backend scripts

Standalone backend scripts live in \`elasticfunnels/scripts/*.js\` and run
server-side. Manage them with the CLI: \`ef scripts list\`, \`ef scripts pull
<codeOrId>\`, \`ef scripts push <pathOrCode>\`, \`ef scripts create <code>\`,
\`ef scripts delete <codeOrId>\`. The first line is a \`// efmeta:{...}\` identity
comment — same rules as above (never write or copy it). Docs:
https://docs.elasticfunnels.io/backend-scripts/overview

## Working with the \`ef\` CLI

Run these from anywhere inside the project (the CLI walks up to find \`.ef/\`):

- \`ef status\` — connection, last sync, entity counts.
- \`ef pull\` — pull everything to disk. \`ef pull pages/about.ef\` for one file.
- \`ef diff\` — show local-vs-server drift before pushing. Run this first.
- \`ef push pages/about.ef\` — push a file (optimistic concurrency). \`--all\` for
  everything, \`--dry-run\` to preview, \`--force\` to override a conflict.
- \`ef preview <slug>\` — get the editor preview URL.
- \`ef list pages --json\` — machine-readable listings (every command takes
  \`--json\`; output goes to stdout, logs to stderr, so piping is safe).

### Safe edit loop

1. \`ef pull\` (or \`ef diff\` to check you're current).
2. Edit \`.ef\` files — **never** the \`efmeta\` line or \`.ef-state.json\`.
3. \`ef diff\` to review what changed.
4. \`ef push <paths…>\`. On an HTTP 409 conflict (exit 4): \`ef pull <path>\`,
   re-apply your change, push again.

Exit codes: 0 ok · 2 usage · 3 auth · 4 conflict · 5 network · 6 server · 7 not found.`;

export function registerClaudeCommand(program: Command): void {
    program
        .command('claude')
        .description('Write ElasticFunnels guidance for Claude Code into CLAUDE.md (idempotent — safe to re-run).')
        .option('--output <path>', 'Target file (default: CLAUDE.md in the project root).')
        .option('--print', 'Print the guidance to stdout instead of writing a file.')
        .action(async (opts: { output?: string; print?: boolean }) => {
            const section = `${BEGIN}\n\n${GUIDE.trim()}\n\n${END}`;

            if (opts.print) {
                process.stdout.write(section + '\n');
                return;
            }

            const root = findProjectRoot() ?? process.cwd();
            const target = opts.output ? path.resolve(opts.output) : path.join(root, 'CLAUDE.md');

            let existing = '';
            try { existing = await fs.promises.readFile(target, 'utf8'); } catch { /* new file */ }

            let next: string;
            let action: string;
            if (existing.includes(BEGIN) && existing.includes(END)) {
                // Replace the managed block in place; leave the rest untouched.
                const before = existing.slice(0, existing.indexOf(BEGIN));
                const after = existing.slice(existing.indexOf(END) + END.length);
                next = `${before}${section}${after}`;
                action = 'Updated ElasticFunnels section in';
            } else if (existing.trim()) {
                next = `${existing.replace(/\s*$/, '')}\n\n${section}\n`;
                action = 'Appended ElasticFunnels section to';
            } else {
                next = `${section}\n`;
                action = 'Created';
            }

            await writeFileAtomic(target, next);
            log.success(`${action} ${target}`);
        });
}
