import * as path from 'path';
import * as fs from 'fs';
import { Command } from 'commander';
import { log } from '../utils/log';
import { findProjectRoot } from '../utils/store';
import { writeFileAtomic } from '../utils/fs';

/**
 * Agent guidance files — `ef claude` and `ef codex`.
 *
 * Both drop the same ElasticFunnels guidance into the file their tool reads, so
 * an agent knows how to work with the synced `elasticfunnels/` tree:
 *
 *   ef claude → CLAUDE.md, plus `.claude/skills/` and a SessionStart hook
 *   ef codex  → AGENTS.md, the convention Codex and several editors read
 *
 * One guidance body, two destinations: a project opened in either tool behaves
 * the same, and there is only one text to keep correct.
 *
 * Idempotent: the guidance sits between markers, so re-running updates that
 * block in place and never disturbs the rest of an existing file.
 * `applyAgentGuidance` is reused by `ef init` so a fresh project gets it too.
 */

/*
 * The managed block is stamped with the CLI version that wrote it, so a project
 * can tell whether its guidance is older than the CLI now reading it. That
 * matters because the guidance documents CLI behaviour: after an upgrade, a
 * stale block has agents working from instructions that no longer match the
 * tool, which is exactly how you get an agent confidently doing the wrong thing.
 *
 * BEGIN_RE also matches the original, unversioned marker so blocks written by
 * <= 0.14.0 are recognised and upgraded rather than duplicated.
 */
const BEGIN_RE = /<!-- ef:begin(?: v[0-9][^\s]*)? \(generated by `ef claude` — safe to re-run\) -->/;
const END = '<!-- ef:end -->';

function beginMarker(version: string): string {
    return `<!-- ef:begin v${version} (generated by \`ef claude\` — safe to re-run) -->`;
}

/** Version of the CLI currently running — the one whose behaviour GUIDE describes. */
export function guidanceVersion(): string {
    try {
        return (require('../../package.json') as { version: string }).version;
    } catch {
        return '0.0.0';
    }
}

/** The version stamped into an existing block, or null if absent/unversioned. */
export function stampedGuidanceVersion(text: string): string | null {
    const m = /<!-- ef:begin v([0-9][^\s]*) \(generated by `ef claude`/.exec(text);
    return m ? m[1] : null;
}

/** Where each tool looks for project instructions. */
export const GUIDANCE_FILES = {
    claude: 'CLAUDE.md',
    codex: 'AGENTS.md',
} as const;

const GUIDE = `# ElasticFunnels project

This project's \`elasticfunnels/\` folder is **synced with the ElasticFunnels
server** by the \`ef\` CLI. Files here represent live server-side entities — edit
them locally, then push.

## Official documentation — check it before you guess

This file is a summary. The docs are the source of truth for anything
server-side, and **a wrong function name breaks the whole page render** (the
live URL starts 404ing), so look a name up rather than inferring it:

- **Backend-script data functions** (customer, orders, products, courses, blog,
  subscriptions, sessions, purchase links, CRM):
  <https://docs.elasticfunnels.io/backend-scripts/data-functions>
- **CRM functions reference** (entries, fields, pipelines, stages, references):
  <https://docs.elasticfunnels.io/crm/post-workflow#crm-functions-reference>
- Docs root: <https://docs.elasticfunnels.io>

For anything about the **CLI itself**, the built-in help is authoritative and
always matches the installed version: \`ef --help\`, \`ef <cmd> --help\`.

## Folder layout (flat)

\`\`\`
elasticfunnels/
  pages/          .ef page files (subdirectories = nested slugs / variants)
  components/     .ef reusable component files
  scripts/        .js standalone backend scripts
  assets/         JS/CSS/media synced from the server
  variables.json  brand variables (editable — syncs on push)
  .ef-state.json  internal sync state — DO NOT EDIT
  .ef-state/      internal snapshot cache — DO NOT EDIT
  .ef-history/    local version snapshots — DO NOT EDIT
\`\`\`

The brand id lives in \`.ef/config.json\`, not in the path.

## CRITICAL: the \`efmeta\` line — NEVER touch it

The **first line** of every synced \`.ef\` file is machine identity — a
\`{{-- efmeta:{...} --}}\` comment (backend \`.js\` scripts use \`// efmeta:{...}\`)
carrying the server \`id\`/\`type\`/\`brandId\`/\`slug\`/\`path\`. It is **path-bound**.

**Rule with NO exceptions: never add, edit, remove, reformat, reorder, or "fix"
the efmeta line, for ANY reason** — not to correct a slug, not to tidy the JSON,
not while resolving a merge. Only ever change the body **below** it.

- The CLI **REJECTS \`ef push\`** (exit 4, conflict) for a file whose efmeta no
  longer matches its tracked identity in \`.ef-state.json\`. If you hit that, run
  \`ef pull <path>\` to restore the correct line — do **not** hand-edit it back.
- **Never write or paste an efmeta line** into code you generate. The CLI stamps
  the correct one on pull/push. (It intentionally holds only stable identity —
  no title, no revision number — so it rarely changes.)
- **When duplicating a page/component**, copy the **body only** — strip the first
  line if it begins with \`{{-- efmeta:\` or \`// efmeta:\`. Otherwise the copy
  inherits the original's identity and can overwrite the wrong server entity.
- The \`{{-- --}}\` comment is stripped at render time and never reaches the browser.

## Do not touch

- \`.ef-state.json\` and \`.ef-state/\` — the CLI manages these (path↔id mapping,
  content hashes, conflict snapshots). Editing them corrupts drift detection.

## \`.ef\` template syntax

\`.ef\` files are HTML with ElasticFunnels' template engine, in **two layers**:

- **Backend** — rendered on the server (and in preview). Use \`@if\`, \`@foreach\`,
  \`{{ ... }}\`. For content fixed at render time (device, query params, brand
  vars, orders, products).
- **Frontend** — runs in the browser, reactive via \`window.efScope\`. Use
  \`<template-if>\`, \`[[ ... ]]\`. For content that must react to client state
  (cart, toggles, form state).

**Match the patterns in the existing \`.ef\` files in this project** — don't
invent directives.

### Backend (server-rendered)

- **Output:** \`{{ var }}\`, \`{{ path.to.value }}\`, \`{{ query.utm_source }}\`
- **Filters** (chain with \`|\`; args via \`:\`): \`{{ name | upper }}\`,
  \`{{ text | truncate:80 }}\`, \`{{ x | default:'Offer' }}\`. Common ones: \`raw\`
  (output HTML unescaped), \`default\`, \`slice\`, \`date\` (e.g. \`date:'dd MMM yyyy'\`),
  \`currency\`, \`number_format\`, \`truncate\`/\`truncatewords\`, \`upper\`/\`lower\`/\`capitalize\`/\`title\`,
  \`json\`, \`timeago\`, \`yesno\`, \`replace\`, \`strip_tags\`, \`length\`, \`first\`/\`last\`,
  \`join\`, \`sort\`, \`round\`.
- **Conditionals:** \`@if(cond) … @elseif(cond) … @else … @endif\`. Operators (word
  form): \`eq neq lt lte gt gte\`; logic \`and\` \`or\`; unary \`!\`. e.g.
  \`@if(orders.length gt 0)\`.
- **Loops:** \`@foreach(item in array) … @endforeach\`.
- **Set a variable:** \`@set(name = expression)\`.
- **Components:** \`@component("component-code", { title: "Home", items: list })\` —
  include a component by its code; args are an object.
- **Inheritance:** \`@extends("wrapper-slug")\`, then \`@block("name") … @endblock\`
  (block name must match the base's \`@block("name")\`).
- **Functions** \`{{ fn(...) }}\`: **\`asset('/main.css')\`** → the brand CDN URL (use
  this for every local asset reference, not a bare path); \`buy('product-code')\`,
  \`upsell(...)\`, \`downsell(...)\`, \`decline(...)\` → purchase links; \`getProduct(s)\`,
  \`getOrders\`, \`getOrder\`, \`getCustomer\`, \`getCourse(s)\`, \`getBlog(s)\`,
  \`getSubscription(s)\`; \`date(...)\`, \`t('key')\` / \`getTranslation\`, \`getBrand\`,
  \`get/setSessionItem\`, \`dump(x)\`. (The full set is large — check existing files.)
- **CRM functions — the casing depends on WHERE you write them.** All take a
  single options object, but the two runtimes register different names, and
  getting this wrong does not degrade gracefully: **an undefined function breaks
  the whole page render and the live URL starts returning 404.**

  | Where | Casing | Set |
  | --- | --- | --- |
  | Templates — \`{{ }}\`/\`@if\` in \`.ef\` files | **PascalCase** | \`EnsureCrmEntity\` \`CreateCrmEntry\` \`GetCrmEntries\` \`GetCrmField(s)\` \`GetCrmFieldValues\` \`SetCrmField(s)\` \`AddCrmFieldValue\` \`ClearCrmEntries\` \`MoveCrmLead\` \`MoveCrmToStage\`/\`ToPipeline\`/\`ToEntity\` \`SetCrmRelation\` \`RemoveCrmRelation\` |
  | Backend scripts — \`<script scope="backend">\` and \`scripts/*.js\` | **camelCase** | \`ensureCrmEntity\` \`getCrmEntries\` \`getCrmField(s)\` \`getCrmFieldValue(s)\` \`setCrmField(s)\` \`setCrmFieldValue(s)\` \`addCrmFieldValue\` \`clearCrmEntries\` \`moveCrmLead\` \`moveCrmToStage\`/\`ToPipeline\`/\`ToEntity\` \`reassignCrmReference\` |

  - **They are not interchangeable.** \`CreateCrmEntry\`, \`SetCrmRelation\` and
    \`RemoveCrmRelation\` exist **only in templates** — calling \`createCrmEntry\`
    in a backend script is an undefined function and takes the page down.
    \`reassignCrmReference\` exists **only in backend scripts**.
  - To create an entry from a **backend script**, use
    \`addCrmFieldValue({slug, fieldKey, value})\` (new entry) or
    \`setCrmFields({slug, fields})\` (upsert) — there is no \`createCrmEntry\`.
  - Verify before you ship: push with \`--draft\`, open the preview URL, and
    confirm the page still renders. A 404 on the live domain is the failure mode.
  - **Anonymous visitors:** these bind to the session customer by default, so a
    logged-out visitor writes nothing. Pass an explicit
    \`referenceType\`/\`referenceId\` (e.g. \`referenceType: 'quiz_visitor'\` plus a
    session UUID), then \`reassignCrmReference(...)\` once they log in. For a
    plain email opt-in, prefer a \`<form>\` + collection — none of this applies.
- **Context** available in \`@if\`/\`{{ }}\`: \`var.*\` (brand variables, e.g.
  \`{{ var.offer_name }}\`); \`request.is_mobile\`/\`is_tablet\`/\`is_customer\`/\`referer\`/\`merchant_code\`;
  \`query.*\` (URL params); \`page\`; \`orders\` (customer orders, newest first; empty
  when no customer).

### Frontend (browser, reactive)

Data lives in \`window.efScope\`; mutate it and call \`notifyScopeUpdated()\` (or fire
\`ef-scope-updated\`) to re-render.

- **Output:** \`[[ expression ]]\` — frontend uses \`[[ ]]\`; backend uses \`{{ }}\`.
- **Condition:** \`<template-if data-condition="cartCount > 0"> … <template-else> … </template-if>\`
  (always \`data-condition\`).
- **Loop:** \`<template-foreach data-each="item in items"> … </template-foreach>\`.
- **Vars scope:** \`<template-vars> … [[ var.name ]] … </template-vars>\`;
  **set:** \`<template-set data-variable="x" data-value="expr">\`;
  **component:** \`<template-component data-component-name="x" data-args='{"k":"v"}'>\`.
- **Bindings:** \`data-ef-text="expr"\`, \`data-ef-html="expr"\` (trusted),
  \`@click="expr"\` / \`data-ef-on:click\`, one-way \`:attr="expr"\`
  (\`:value\`/\`:checked\`/\`:disabled\`/\`:style\`), two-way \`data-template-value="path"\`
  (v-model for inputs/selects/textareas).

## Forms → collections

Write a plain \`<form>\` with \`name\`d inputs and **no \`action\` attribute**. On
\`ef push\` the backend auto-creates a collection and rewrites the form for you,
setting \`action="/api/collection/<code>/store"\`, \`data-collection\`,
\`data-collection-id\`, \`method="post"\` and success/error message elements.

- **Do not write \`action\`, \`data-collection\` or \`data-collection-id\` yourself.**
  A non-empty \`action\` is the documented **opt-out** — the form is left alone.
  Use that only for genuinely non-lead forms (search, filters, external
  webhooks).
- **Do not invent collection codes.** To target an *existing* collection, use
  its real code. \`COLLECTION_CODE\` is a placeholder, not a code: pushing it
  creates a brand-new collection.
- Checkout/payment forms are auto-detected and skipped — don't touch them.

**\`ef push\` overwrites your local file with the server's rewritten HTML**, so
after pushing a page with a form, **re-read the file before editing it again**.
Editing your pre-push copy and pushing again re-sends the stale markup and
creates a *second* collection. \`ef push\` prints the codes it created.

> **Auto-creation is skipped when the page contains backend template syntax** —
> any \`{{ … }}\` or \`@if\`/\`@foreach\`/\`@extends\`/\`@set\` etc. anywhere in the file
> (the server's HTML parser would mangle them). \`ef push\` warns when it skips
> for this reason. This is common, so know the fallback below.

### The reliable route: create the collection first

Works on **every** page, including template-heavy ones, and lets you write
correct markup in one pass instead of pushing and re-reading:

\`\`\`bash
ef collections create "Newsletter" --field Email:email:required --json
# → { "code": "newsletter-a1b2", … }
\`\`\`

Then write the form against that code — and because \`action\` is set, the server
leaves your markup exactly as written:

\`\`\`html
<form action="/api/collection/newsletter-a1b2/store" method="post">
  <input type="email" name="email" required>
  <button type="submit">Subscribe</button>
</form>
\`\`\`

Field spec is \`Name[:type[:required]]\`; types: \`text, email, number, checkbox,
password, textarea, select, hidden\`. Repeat \`--field\` per field.

### A collection **is** a CRM entity

Creating a collection provisions a matching CRM entity behind it — a
"Form Submissions" pipeline, a first stage, and the collection's fields mirrored
as CRM fields. So form submissions are CRM records: readable with
\`ef crm entries <entity>\`, movable through stages, and usable from the CRM
functions above. You do **not** need a backend script to capture a lead —
the form writes to CRM by itself.

### Verify it actually stores

Never assume a form works because the page renders — a mis-wired form returns
success and drops the data:

\`\`\`bash
ef collections list              # codes + entry counts
ef collections get <code>        # fields + the exact action URL to use
ef collections entries <code>    # did a submission actually land?
\`\`\`

## Domains — putting a page on one

Assigning a domain is a **page** setting, not something under \`ef domains\`:

\`\`\`bash
ef domains list                                              # what exists, and its status
ef pages settings pricing --domain shop.example.com          # attach the page
ef pages settings home --domain shop.example.com --homepage  # attach + serve at the domain root
ef pages settings pricing --domain none                      # detach
\`\`\`

\`--domain\` takes a domain **name or numeric id**. \`--homepage\` is what makes a
page answer at \`https://<domain>/\` rather than \`/<slug>\`; exactly one page per
domain should have it. A domain only serves traffic once validated — check with
\`ef domains list\`, and use \`ef domains records <domain>\` / \`ef domains validate
<domain>\` if it isn't.

## Page variants (A/B tests)

Variants of a page live under a subfolder named after the base slug:
\`pages/my-page/my-page.ef\` (active — holds the main \`slug\`) plus
\`pages/my-page/my-page-v2.ef\` (variant — uses \`variant_slug\`). Single pages sit
directly under \`pages/\`. Change a slug with \`ef pages settings <slug> --slug <new>\`
(the CLI renames the local file to match).

## Backend scripts

Standalone scripts in \`elasticfunnels/scripts/*.js\` run **server-side** on page
requests. The first line is a \`// efmeta:{...}\` identity comment (same rules —
never write or copy it).

- **Globals (read-only):** request/query/customer/order context.
- **Actions (side effects):** session & cookies, \`redirect(url)\` (stops
  rendering), set template variables, custom response, response headers.
- **Data functions:** the same helpers as templates — \`getCustomer\`, \`getOrders\`,
  \`getProduct(s)\`, courses, blog, purchase links (\`buy\`/\`upsell\`),
  \`asset('/main.css')\`, CRM functions.
- **HTTP:** can call external APIs. **Cross-file imports:** a script can import
  other backend-script modules.
- Manage with the CLI: \`ef scripts list | pull <codeOrId> | push <pathOrCode> | create <code> | delete <codeOrId>\`.
- Docs: https://docs.elasticfunnels.io/backend-scripts/overview

## Working with the \`ef\` CLI

Run from anywhere inside the project (the CLI walks up to find \`.ef/\`).

> ### Never assume a capability is missing — ask the CLI
>
> \`ef --help\` lists every command; \`ef <cmd> --help\` and \`ef <cmd> <sub> --help\`
> give the flags, examples and exit codes for each. **Run them before concluding
> that something is impossible, and before guessing a flag name.** The help text
> is generated from the code, so it is always correct for the version installed —
> this document is a summary and can lag it.
>
> Concretely: if you are about to say "the CLI can't do X", run \`ef --help\` and
> the \`--help\` of the most likely command first. Assigning a page to a domain,
> for instance, is not under \`ef domains\` — it is \`ef pages settings --domain\`.

**Every command** (as of the version that wrote this file):

\`\`\`
init login auth reset whoami status list preview get pull push pages components
products scripts assets variables diff ask claude codex mcp install-highlighter
collections
update config watch lint domains crm funnels
\`\`\`

Most-used, by task:

| I want to… | Command |
| --- | --- |
| See what exists | \`ef list pages\\|components\\|scripts\\|assets\\|folders\\|templates\` |
| Get current server state | \`ef pull\` (whole brand) · \`ef pull pages/x.ef\` (one file) |
| See my uncommitted changes | \`ef diff\` |
| Ship a change | \`ef push pages/x.ef\` |
| Create a page / component | \`ef pages create <slug>\` · \`ef components create <code>\` |
| Rename / re-slug a page | \`ef pages settings <slug> --slug <new>\` |
| Put a page on a domain | \`ef pages settings <slug> --domain <name> [--homepage]\` |
| Manage domains + DNS | \`ef domains list\\|add\\|records\\|validate\\|remove\` |
| Publish a draft | \`ef pages publish <slug>\` |
| Preview / live URL | \`ef preview <slug>\` |
| Check my work statically | \`ef lint\` |
| Brand variables | \`ef variables get\\|set\\|pull\\|push\` |
| Lead forms / form stores | \`ef collections list\` · \`ef collections create <name> --field Email:email:required\` · \`ef collections entries <code>\` |
| CRM data | \`ef crm entities\\|pipelines\\|stages\\|fields\\|entries\` |
| Split tests / funnel graphs | \`ef pages events …\` · \`ef funnels …\` (use the \`ef-page-events\` skill) |
| Fix a rejected credential | \`ef login\` |
| Update the CLI itself | \`ef update\` (\`--check\` to just look) |
| Check config / identity | \`ef status\` · \`ef whoami\` · \`ef config get\` |

- \`ef status\` — connection, last sync, entity counts.
- \`ef pull\` — pull everything. \`ef pull pages/about.ef\` for one file.
- \`ef diff\` — show local-vs-server drift before pushing. Run this first.
- \`ef push pages/about.ef\` — push a file (optimistic concurrency). \`--all\` for
  everything, \`--dry-run\` to preview, \`--force\` to override a conflict.
- \`ef watch\` — auto-push files as you edit and save them (publishes by default;
  \`--draft\` to save drafts). Ideal alongside an AI editor — save and it's live.
- \`ef pages push <slugOrPath>\` · \`ef components push <codeOrPath>\` ·
  \`ef scripts push <pathOrCode>\` — push one entity by path or code.
- \`ef components create <code>\` · \`ef pages create <slug>\` — create an entity.
- \`ef lint [paths…]\` — statically validate \`.ef\` pages/components/scripts
  (unclosed \`{{ }}\`/\`[[ ]]\`, unknown \`@directives\`/filters, unbalanced blocks,
  script parse errors). Exits non-zero on errors; \`--strict\` fails on warnings too.
- \`ef variables set <key> <value>\` — set one brand variable (dotted keys nest,
  e.g. \`brand.name\`; JSON-typed values; \`@file\` reads a file). \`ef variables get/pull/push\`.
- \`ef crm entities | pipelines <entity> | stages <pipeline> | fields <entity> | entries <entity>\`
  — read CRM. Create/update/delete with \`ef crm <group> create/update/delete\`. Entity args
  take an id **or slug**. Entries are Elasticsearch docs (string ids); \`values\` is a flat map.
  Complex payloads: \`--input-json '{…}'\` / \`--input-file <path|->\` (flags override the JSON);
  \`--generate-skeleton\` prints an example payload.
- **Page events + funnel graphs** — Drawflow JSON graphs (split tests, redirects, tags, popups):
  - **To AUTHOR or edit a graph from a request** ("load the white page unless \`?test=1\`",
    "split test this component", "redirect affiliate traffic"), use the **\`ef-page-events\` skill**
    (\`ef claude\` installs it into \`.claude/skills/\`). It has the graph model, the node reference,
    the two silent-no-op traps (LOAD vs REDIRECT; typed conditions need their compiled \`script_rule\`),
    and worked examples. Load it before hand-building any \`.events.json\`/\`.flow.json\`.
  - **Always pull first.** Push REFUSES (exit 4) not only on server drift but also when you never
    pulled a page/funnel that already has a graph — so a hand-authored or copied file can't clobber
    server state you never saw. Fresh-create (server has none) is still allowed without a pull.
  - \`ef pages events pull|push|diff|validate|vocabulary <slug>\` → \`pages/<slug>.events.json\`
    (nested slugs preserved). NOT pulled by \`ef pull\` unless \`--events\`.
  - \`ef funnels pull|push|diff <code>\` → \`funnels/<code>.flow.json\` (the funnel's builder graph);
    \`ef funnels debug-flow|product-flow <code>\` print the compiled READ-ONLY artifacts.
  - Structure: \`{ "drawflow": { "Home": { "data": { "<id>": { id, name, data:{type,…}, inputs, outputs, pos_x, pos_y } } } } }\`.
    The \`<split-test>\` container in the \`.ef\` markup shows the default; its variants live in this graph.
  - Node types + connection rules (\`only_on\`, \`max_per_output\`, \`one_of_type\`) are the SERVER's
    source of truth — do NOT hand-invent node types. Validate deeply with \`ef pages events validate\`
    (server, always current) and structurally with \`ef lint\` (offline JSON/shape).
  - These are structured JSON, so there is NO auto-merge: if the server changed since you pulled,
    push REFUSES (exit 4). See the delta with \`ef diff pages/x.events.json\` / \`ef diff funnels/x.flow.json\`,
    then pick a side — \`--force\` on push (keep local) or \`pull --force\` (take server).
  - A funnel's \`flow\`/\`product_flow\`/\`variant_seeds\` are read-only (server regenerates on save) — never edit them.
- \`ef config get\` / \`ef config set saveMode direct\` — view/change project config.
- \`ef preview <slug>\` — editor preview URL.
- \`ef list pages --json\` — machine-readable listings (every command takes
  \`--json\`; output goes to stdout, logs to stderr, so piping is safe).

### Save modes (draft vs direct)

\`ef push\` **publishes** by default (\`saveMode: direct\`). Pass \`--draft\` to save a
draft that isn't live until published; \`--direct\` forces a publish. A draft push
prints a warning that it's not live. Change the project default with
\`ef config set saveMode draft|direct\`.

### ALWAYS work from current server state

These files mirror live server entities that **other people and the visual page
editor also change**. A local copy goes stale the moment someone edits a page in
the app. Working from a stale copy means either clobbering their change or
having your push rejected after you already did the work.

- **Start every session with a pull.** \`ef pull --if-stale 30\` is a no-op when
  the last pull was under 30 minutes ago, so it is free to run every time.
  (\`ef claude\` installs a SessionStart hook that runs exactly this — but run it
  yourself if you are not sure the hook fired.)
- **Before touching a page you have not already worked on this session, pull that
  page:** \`ef pull pages/<slug>.ef\`. A pull at session start does not help if you
  start editing an hour later.
- Same for a component (\`ef pull components/<code>.ef\`), a backend script, and a
  graph (\`ef pages events pull <slug>\`).
- \`ef status\` prints when the last pull happened. If it reads in hours, pull.

### Safe edit loop

1. \`ef pull\` (or \`ef diff\` to check you're current).
2. Edit \`.ef\` files — **never** the \`efmeta\` line or \`.ef-state.json\`.
3. \`ef diff\` to review what changed.
4. \`ef push <paths…>\`. On an HTTP 409 conflict (exit 4): \`ef pull <path>\`,
   re-apply your change, push again.

**Safety (lost-update protection):** \`ef push\` REFUSES (exit 4) if the entity
changed on the server since you last pulled — it prints \`Changes rejected: <path>
changed on the server …\` and uploads nothing, so you can't clobber someone else's
edit. To resolve: \`ef diff --server <path>\` shows the real server-vs-local diff;
\`ef pull --merge <path>\` does a git-style 3-way merge (clean auto-merge, or
\`<<<<<<< / ======= / >>>>>>>\` markers on overlap — a file with unresolved markers
is itself refused on push); \`ef push <path> --force\` overwrites the server anyway.
\`ef pull\` also keeps a file you've edited locally and warns (\`--force\` to take the
server's, \`--merge\` to merge). Overwritten files are copied to \`.ef-history/\` first.

Exit codes: 0 ok · 2 usage · 3 auth · 4 conflict · 5 network · 6 server · 7 not found.`;

/** The marked, ready-to-embed guidance block, stamped with this CLI's version. */
export function renderClaudeSection(): string {
    return `${beginMarker(guidanceVersion())}\n\n${GUIDE.trim()}\n\n${END}`;
}

/**
 * Write / refresh the ElasticFunnels guidance block in `target` (a CLAUDE.md or
 * AGENTS.md path). Idempotent: replaces the managed block in place, appends it
 * to an existing file, or creates the file. Returns what it did.
 */
export async function applyAgentGuidance(target: string): Promise<'created' | 'updated' | 'appended'> {
    const section = renderClaudeSection();
    let existing = '';
    try { existing = await fs.promises.readFile(target, 'utf8'); } catch { /* new file */ }

    let next: string;
    let action: 'created' | 'updated' | 'appended';
    const begin = BEGIN_RE.exec(existing);
    if (begin && existing.includes(END)) {
        const before = existing.slice(0, begin.index);
        const after = existing.slice(existing.indexOf(END) + END.length);
        next = `${before}${section}${after}`;
        action = 'updated';
    } else if (existing.trim()) {
        next = `${existing.replace(/\s*$/, '')}\n\n${section}\n`;
        action = 'appended';
    } else {
        next = `${section}\n`;
        action = 'created';
    }
    await writeFileAtomic(target, next);
    return action;
}

/**
 * Bring a project's guidance blocks up to the running CLI's version.
 *
 * The guidance documents how *this* CLI behaves. After `ef update`, a project
 * whose CLAUDE.md was written by an older version is actively misleading — it
 * describes commands and behaviour that have since changed, and an agent has no
 * way to know it is reading stale instructions. So any command that already
 * loads the project re-stamps them.
 *
 * Deliberately narrow:
 *   - only rewrites files that ALREADY contain a managed block, so a project
 *     set up with `--no-claude` is never given one behind the user's back;
 *   - no-ops when the stamp already matches, making the common path two small
 *     reads and no writes;
 *   - never throws. A read-only checkout must not fail someone's pull.
 */
export async function refreshGuidanceIfStale(projectRoot: string): Promise<string[]> {
    const current = guidanceVersion();
    const updated: string[] = [];
    for (const name of Object.values(GUIDANCE_FILES)) {
        const target = path.join(projectRoot, name);
        try {
            const existing = await fs.promises.readFile(target, 'utf8');
            if (!BEGIN_RE.test(existing) || !existing.includes(END)) continue;
            if (stampedGuidanceVersion(existing) === current) continue;
            await applyAgentGuidance(target);
            updated.push(name);
        } catch { /* missing or unwritable — leave it alone */ }
    }
    return updated;
}

/**
 * Locate the bundled Claude Code skills. They ship under `assets/skills/` at the
 * package root; this file runs from `out/commands/`, so the root is two levels
 * up. The extra candidate keeps `npm link` / ts-node layouts working in dev.
 */
function findSkillsSourceDir(): string | null {
    const roots = [
        path.resolve(__dirname, '..', '..', 'assets', 'skills'),
        path.resolve(__dirname, '..', '..', '..', 'assets', 'skills'),
    ];
    for (const dir of roots) {
        try {
            if (fs.statSync(dir).isDirectory()) return dir;
        } catch { /* try next */ }
    }
    return null;
}

/**
 * Install the bundled skills into `<root>/.claude/skills/<name>/SKILL.md`.
 * Idempotent: overwrites the managed SKILL.md in place so re-running picks up a
 * newer CLI's copy. Returns the skill names written (empty if none bundled).
 */
export async function installBundledSkills(root: string): Promise<string[]> {
    const src = findSkillsSourceDir();
    if (!src) return [];
    const written: string[] = [];
    for (const name of fs.readdirSync(src)) {
        const skillFile = path.join(src, name, 'SKILL.md');
        try {
            if (!fs.statSync(skillFile).isFile()) continue;
        } catch { continue; }
        const body = await fs.promises.readFile(skillFile, 'utf8');
        const destDir = path.join(root, '.claude', 'skills', name);
        await fs.promises.mkdir(destDir, { recursive: true });
        await writeFileAtomic(path.join(destDir, 'SKILL.md'), body);
        written.push(name);
    }
    return written;
}

/** The command the session hook runs. Cheap by design — a no-op when fresh. */
const SESSION_PULL_COMMAND = 'ef pull --if-stale 30';

/**
 * Install a Claude Code SessionStart hook that refreshes the project before the
 * model reads anything.
 *
 * Guidance alone is not enough here. "Pull before you start" is a rule the model
 * has to remember on every single session, and forgetting it silently produces
 * work against stale pages — the exact failure that costs a rejected push or
 * someone else's edit. A hook is executed by the harness, so it cannot be
 * forgotten. `--if-stale` keeps it free when the project is already current.
 *
 * Merges into any existing `.claude/settings.json` rather than replacing it, and
 * will not add a second copy of its own hook.
 */
export async function installSessionHook(root: string): Promise<'created' | 'added' | 'present'> {
    const settingsPath = path.join(root, '.claude', 'settings.json');

    let settings: Record<string, any> = {};
    let existed = false;
    try {
        settings = JSON.parse(await fs.promises.readFile(settingsPath, 'utf8'));
        existed = true;
    } catch {
        // Missing or unparseable. An unparseable file is the user's, so treat it
        // as absent rather than overwriting hand-written settings we can't read.
        settings = {};
    }

    if (!settings.hooks || typeof settings.hooks !== 'object') settings.hooks = {};
    if (!Array.isArray(settings.hooks.SessionStart)) settings.hooks.SessionStart = [];

    const already = JSON.stringify(settings.hooks.SessionStart).includes(SESSION_PULL_COMMAND);
    if (already) return 'present';

    settings.hooks.SessionStart.push({
        hooks: [{ type: 'command', command: SESSION_PULL_COMMAND }],
    });

    await fs.promises.mkdir(path.dirname(settingsPath), { recursive: true });
    await writeFileAtomic(settingsPath, JSON.stringify(settings, null, 2) + '\n');

    return existed ? 'added' : 'created';
}

export function registerClaudeCommand(program: Command): void {
    program
        .command('claude')
        .description('Write ElasticFunnels guidance for Claude Code into CLAUDE.md, install the ef skills, and add a session hook that keeps the project current (idempotent — safe to re-run).')
        .option('--output <path>', 'Target file (default: CLAUDE.md in the project root).')
        .option('--print', 'Print the guidance to stdout instead of writing a file.')
        .option('--no-skills', 'Skip installing the bundled Claude Code skills into .claude/skills/.')
        .option('--no-hook', 'Skip the SessionStart hook that runs "ef pull --if-stale" before each session.')
        .action(async (opts: { output?: string; print?: boolean; skills?: boolean; hook?: boolean }) => {
            if (opts.print) {
                process.stdout.write(renderClaudeSection() + '\n');
                return;
            }
            const root = findProjectRoot() ?? process.cwd();
            const target = opts.output ? path.resolve(opts.output) : path.join(root, GUIDANCE_FILES.claude);
            const action = await applyAgentGuidance(target);
            const verb = action === 'created' ? 'Created' : action === 'updated' ? 'Updated ElasticFunnels section in' : 'Appended ElasticFunnels section to';
            log.success(`${verb} ${target}`);

            if (opts.skills !== false) {
                const installed = await installBundledSkills(root);
                if (installed.length > 0) {
                    log.success(`Installed skill${installed.length > 1 ? 's' : ''} into .claude/skills/: ${installed.join(', ')}.`);
                    log.detail('Claude Code loads these on demand — e.g. ask it to "create a page event to load the white page unless ?test=1".');
                }
            }

            if (opts.hook !== false) {
                const hook = await installSessionHook(root);
                if (hook === 'present') {
                    log.detail('SessionStart hook already present in .claude/settings.json.');
                } else {
                    log.success(`SessionStart hook ${hook === 'created' ? 'written to' : 'added to'} .claude/settings.json — runs "${SESSION_PULL_COMMAND}" so each session starts on current data.`);
                }
            }
        });
}

export function registerCodexCommand(program: Command): void {
    program
        .command('codex')
        .alias('agents')
        .description('Write the same ElasticFunnels guidance into AGENTS.md, which Codex and several editors read (idempotent — safe to re-run).')
        .option('--output <path>', `Target file (default: ${GUIDANCE_FILES.codex} in the project root).`)
        .option('--print', 'Print the guidance to stdout instead of writing a file.')
        .action(async (opts: { output?: string; print?: boolean }) => {
            if (opts.print) {
                process.stdout.write(renderClaudeSection() + '\n');
                return;
            }
            const root = findProjectRoot() ?? process.cwd();
            const target = opts.output ? path.resolve(opts.output) : path.join(root, GUIDANCE_FILES.codex);
            const action = await applyAgentGuidance(target);
            const verb = action === 'created' ? 'Created' : action === 'updated' ? 'Updated ElasticFunnels section in' : 'Appended ElasticFunnels section to';
            log.success(`${verb} ${target}`);
            log.detail('Codex has no skills or hooks, so the pull-before-you-work rule lives in the guidance text itself.');
        });
}
